# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module(name = "ads_oneshop")

bazel_dep(name = "rules_python", version = "1.7.0")
bazel_dep(name = "protobuf", version = "29.5")
bazel_dep(name = "rules_pkg", version = "1.1.0")
bazel_dep(name = "rules_oci", version = "2.2.6")
bazel_dep(name = "rules_distroless", version = "0.5.3")
bazel_dep(name = "rules_go", version = "0.57.0")
bazel_dep(name = "gazelle", version = "0.45.0")
bazel_dep(name = "bazel_skylib", version = "1.8.1")
bazel_dep(name = "rules_shell", version = "0.6.0")
bazel_dep(name = "toolchains_protoc", version = "0.5.0")
bazel_dep(name = "bazel_lib", version = "3.1.0")
bazel_dep(name = "googleapis", version = "0.0.0-20260728-b8486a2f")

python_version = "3.13"

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.defaults(python_version = python_version)
python.toolchain(python_version = python_version)
use_repo(python, my_toolchain = "python_3_13")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    # # copybara:strip_begin
    # # NOTE: need to update ~/.bazelrc with the following content:
    # #   common --credential_helper=us-python.pkg.dev=%workspace%/cred_helper.sh
    # experimental_index_url = "https://us-python.pkg.dev/artifact-foundry-prod/python-3p-trusted/simple/",
    # extra_pip_args = ["--index-url", "https://us-python.pkg.dev/artifact-foundry-prod/python-3p-trusted/simple/"],
    # # copybara:strip_end
    hub_name = "acit_deps",
    python_version = python_version,
    requirements_lock = "//:requirements_lock.txt",
)
pip.override(
    file = "gcsfs-2026.6.0-py3-none-any.whl",
    patch_strip = 1,
    patches = ["//:gcsfs_compat.patch"],
)
use_repo(pip, "acit_deps")

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.24.6")

go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")
go_deps.gazelle_override(
    directives = [
        "gazelle:go_visibility //visibility:public",
    ],
    path = "github.com/GoogleCloudPlatform/protoc-gen-bq-schema/v3",
)
use_repo(
    go_deps,
    protoc_gen_bq_schema = "com_github_googlecloudplatform_protoc_gen_bq_schema_v3",
)

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.toolchains(name = "oci_tools")
oci.pull(
    name = "oci_beam_python",
    # 2.69.0
    digest = "sha256:10cf8bedf0a3e28095159cf7c94d4d33fef8b57877f20f46fcd0ac16644333d6",
    image = "docker.io/apache/beam_python3.13_sdk",
    platforms = [
        "linux/amd64",
    ],
)
use_repo(
    oci,
    "oci_beam_python",
    "oci_beam_python_linux_amd64",
    "oci_tools_crane_toolchains",
    "oci_tools_regctl_toolchains",
)

apt = use_extension(
    "@rules_distroless//apt:extensions.bzl",
    "apt",
    dev_dependency = True,
)
apt.install(
    name = "debian",
    lock = "//acit:debian.lock.json",
    manifest = "//acit:debian.yaml",
)
use_repo(apt, "debian")

# Override the toolchain registration from the protobuf module
protoc = use_extension("@toolchains_protoc//protoc:extensions.bzl", "protoc")
use_repo(
    protoc,
    "toolchains_protoc_hub",
    # Make protoc explicitly available
    "toolchains_protoc_hub.linux_x86_64",
)

register_toolchains("@toolchains_protoc_hub//:all")

register_toolchains("//tools/toolchains:all")
