# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_python//python:py_binary.bzl", "py_binary")
load("@rules_python//python:py_library.bzl", "py_library")
load("@rules_python//python:py_test.bzl", "py_test")

package(default_visibility = ["//acit:__subpackages__"])

py_library(
  name = "oauth_lib",
  srcs = ["oauth.py"],
)

py_binary(
  name = "oauth",
  srcs = ["oauth.py"],
  deps = [":oauth_lib"],
)

py_test(
  name = "oauth_test",
  main = "test_oauth.py",
  srcs = ["test_oauth.py"],
  deps = [
      ":oauth_lib",
      "@acit_deps//absl_py",
  ],
)
